# Generated by Django 5.0.4 on 2024-04-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='last_active_date',
            field=models.DateField(default=None),
        ),
    ]
