# Generated by Django 5.0.4 on 2024-04-18 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(max_length=10)),
                ('workouts', models.IntegerField(max_length=10)),
                ('longest_day_streak', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='exercises',
            name='saved',
            field=models.ManyToManyField(blank=True, null=True, related_name='save_exc', to=settings.AUTH_USER_MODEL),
        ),
    ]
