# Generated by Django 5.0.4 on 2024-04-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_streak_last_active_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Streak',
        ),
    ]
