# Generated by Django 5.0.4 on 2024-04-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_exercises_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='difficulty',
        ),
    ]
