# Generated by Django 5.0.4 on 2024-04-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_remove_exercises_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
    ]
