# Generated by Django 5.0.4 on 2024-04-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_exercises_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='difficulty',
        ),
    ]
