# Generated by Django 5.0.4 on 2024-04-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_remove_exercises_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'medium'), ('hard', 'Hard')], max_length=10, null=True),
        ),
    ]
