# Generated by Django 5.0.4 on 2024-04-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='workouts',
            field=models.CharField(max_length=200),
        ),
    ]
