# Generated by Django 5.0.4 on 2024-04-20 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_alter_progress_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='trained_muscles',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='workouts',
        ),
        migrations.AddField(
            model_name='progress',
            name='trained_muscles',
            field=models.ManyToManyField(blank=True, null=True, related_name='trained_muscle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progress',
            name='workouts',
            field=models.ManyToManyField(blank=True, null=True, related_name='done_workouts', to='exercise.exercises'),
        ),
    ]
