# Generated by Django 5.0.4 on 2024-04-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_alter_progress_workouts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
