# Generated by Django 5.0.4 on 2024-04-20 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0014_delete_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='completed',
            field=models.ManyToManyField(blank=True, null=True, related_name='complete_exercise', to=settings.AUTH_USER_MODEL),
        ),
    ]
